# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "libnanvix"
version = "0.0.1"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Nanvix System Library"
homepage = "https://github.com/nanvix"

[lib]
crate-type = ["lib"]

[dependencies]
kcall = { path = "../kcall" }
